echo ""
echo "           wake up, Neo..."
echo "        the matrix has you"
echo "      follow the white rabbit."
echo ""
echo "          knock, knock, Neo."
echo ""
echo "                        (\`.         ,-,"
echo "                        \` \`.    ,;' /"
echo "                         \`.  ,'/ .'"
echo "                          \`. X /.'"
echo "                .-;--''--.._\` \` ("
echo "              .'            /   \`"
echo "             ,           \` '   Q '"
echo "             ,         ,   \`._    "
echo "          ,.|         '     \`-.;_'"
echo "          :  . \`  ;    \`  \` --,.._;"
echo "           ' \`    ,   )   .'"
echo "              \`._ ,  '   /_"
echo "                 ; ,''-,;' \`\`-"
echo "                  \`\`-..__\`\`--\`"
echo ""
