echo ""
echo "  Metasploit Park, System Security Interface"
echo "  Version 4.0.5, Alpha E"
echo "  Ready..."
echo "  > access security"
echo "  access: PERMISSION DENIED."
echo "  > access security grid"
echo "  access: PERMISSION DENIED."
echo "  > access main security grid"
echo "  access: PERMISSION DENIED....and..."
echo "  YOU DIDN'T SAY THE MAGIC WORD!"
echo "  YOU DIDN'T SAY THE MAGIC WORD!"
echo "  YOU DIDN'T SAY THE MAGIC WORD!"
echo "  YOU DIDN'T SAY THE MAGIC WORD!"
echo "  YOU DIDN'T SAY THE MAGIC WORD!"
echo "  YOU DIDN'T SAY THE MAGIC WORD!"
echo "  YOU DIDN'T SAY THE MAGIC WORD!"
